export interface AssetOption {
  label: string;
  symbol: string;
}

export interface IndexOption {
  label: string;
  insCode: string;
}

// Sourced verbatim from "Analysis PlayGround.ipynb" cell outputs (get_symbols() scrape of
// tgju.org and get_tsetmc_all_index() live call to GetIndexB1LastAll) — the same instrument
// lists the source notebook validated, not hand-guessed. tgju has no CORS-enabled endpoint
// that lists all instruments itself (see docs/BACKLOG.md T-007), so this snapshot is the
// source of truth until re-scraped.
export const TGJU_ASSETS: AssetOption[] = [
  { label: "مثقال طلا", symbol: "mesghal" },
  { label: "طلای 18 عیار", symbol: "geram18" },
  { label: "طلای 24 عیار", symbol: "geram24" },
  { label: "طلای دست دوم", symbol: "gold_mini_size" },
  { label: "دلار", symbol: "price_dollar_rl" },
  { label: "یورو", symbol: "price_eur" },
  { label: "پوند", symbol: "price_gbp" },
  { label: "درهم امارات", symbol: "price_aed" },
  { label: "آبشده نقدی", symbol: "gold_futures" },
  { label: "آبشده بنکداری", symbol: "gold_melted_wholesale" },
  { label: "آبشده کمتر از کیلو", symbol: "gold_world_futures" },
  { label: "آبشده شنبه ای", symbol: "gold_melted_transfer" },
  { label: "سکه بهار آزادی", symbol: "sekeb" },
  { label: "سکه امامی", symbol: "sekee" },
  { label: "نیم سکه", symbol: "nim" },
  { label: "ربع سکه", symbol: "rob" },
  { label: "سکه گرمی", symbol: "gerami" },
  { label: "قیمت نقره", symbol: "silver_999" },
  { label: "کرون سوئد", symbol: "price_sek" },
  { label: "کرون نروژ", symbol: "price_nok" },
  { label: "دلار کانادا", symbol: "sana_sell_cad" },
  { label: "لیر ترکیه", symbol: "sana_sell_try" },
  { label: "ین ژاپن", symbol: "price_jpy" },
  { label: "رینگیت مالزی", symbol: "price_myr" },
  { label: "دینار کویت", symbol: "price_kwd" },
  { label: "لیر سوریه", symbol: "price_syp" },
  { label: "روبل روسیه", symbol: "price_rub" },
  { label: "ریال عمان", symbol: "price_omr" },
  { label: "دلار سنگاپور", symbol: "price_sgd" },
  { label: "دینار عراق", symbol: "price_iqd" },
  { label: "افغانی", symbol: "price_afn" },
  { label: "منات آذربایجان", symbol: "price_azn" },
  { label: "دینار بحرین", symbol: "price_bhd" },
  { label: "لاری گرجستان", symbol: "price_gel" },
  { label: "ریال عربستان", symbol: "price_sar" },
  { label: "یوان چین", symbol: "bank_cny" },
  { label: "طلای 18 عیار / 740", symbol: "gold_740k" },
  { label: "مثقال / عیار جهانی", symbol: "gold_17" },
  { label: "مثقال / حواله دلار", symbol: "gold_17_transfer" },
  { label: "گرم نقره ۹۲۵", symbol: "silver_925" },
  { label: "حباب سکه امامی", symbol: "coin_blubber" },
  { label: "حباب سکه بهار آزادی", symbol: "sekeb_blubber" },
  { label: "حباب نیم سکه", symbol: "nim_blubber" },
  { label: "حباب ربع سکه", symbol: "rob_blubber" },
  { label: "حباب سکه گرمی", symbol: "gerami_blubber" },
  { label: "تمام سکه رفاه", symbol: "gc15" },
  { label: "تمام سکه آینده", symbol: "gc18" },
  { label: "تمام سکه سامان", symbol: "gc17" },
  { label: "گواهی سپرده سکه طلا", symbol: "go02" },
  { label: "انس طلا", symbol: "ons" },
  { label: "انس نقره", symbol: "silver" },
  { label: "انس پلاتین", symbol: "platinum" },
  { label: "انس پالادیوم", symbol: "palladium" },
  { label: "آلومینیوم", symbol: "basemetal-aluminum" },
  { label: "سرب", symbol: "basemetal-lead" },
  { label: "روی", symbol: "basemetal-zinc" },
  { label: "نیکل", symbol: "basemetal-nickel" },
  { label: "کبالت", symbol: "cobalt" },
  { label: "قلع", symbol: "basemetal-tin" },
  { label: "مس / بازار لندن", symbol: "basemetal-london-copper" },
  { label: "مس / بازار آمریکا", symbol: "basemetal-copper" },
  { label: "نفت خام (WTI)", symbol: "energy-crude-oil" },
  { label: "نفت برنت", symbol: "energy-brent-oil" },
  { label: "نفت اپک", symbol: "oil_opec" },
  { label: "نفت کوره", symbol: "energy-heating-oil" },
  { label: "نفت سبک لوئیزیانا", symbol: "louisiana-light" },
  { label: "پنبه", symbol: "commodities-us-cotton" },
  { label: "جو", symbol: "commodities-oats" },
  { label: "برنج", symbol: "commodities-rough-rice" },
  { label: "ذرت", symbol: "commodities-us-corn" },
  { label: "قهوه", symbol: "commodities-london-wheat" },
  { label: "گندم / بازار آمریکا", symbol: "commodities-us-wheat" },
  { label: "کاکائو / بازار آمریکا", symbol: "commodities-us-cocoa" },
  { label: "شکر / بازار آمریکا", symbol: "commodities-us-sugar" },
  { label: "گازوییل", symbol: "energy-london-gas-oil" },
  { label: "بنزین", symbol: "energy-gasoline-rbob" },
  { label: "گاز طبیعی", symbol: "energy-natural-gas" },
  { label: "ذغال سنگ", symbol: "energy-carbon-emissions" },
  { label: "اتانول", symbol: "energy-ethanol-futures-contracts" },
  { label: "ال ان جی ژاپن / کره", symbol: "lng-japan-korea-marker" },
  { label: "الوار", symbol: "commodities-lumber" },
  { label: "آب پرتقال", symbol: "commodities-orange-juice" },
  { label: "سویا", symbol: "commodities-us-soybeans" },
  { label: "کنجاله سویا", symbol: "commodities-us-soybean-meal" },
  { label: "روغن سویا", symbol: "commodities-us-soybean-oil" },
  { label: "کاکائو / بازار لندن", symbol: "commodities-london-cocoa" },
  { label: "شکر / بازار لندن", symbol: "commodities-london-sugar" },
  { label: "یورو / دلار", symbol: "eur-usd-ask" },
  { label: "پوند / دلار", symbol: "gbp-usd-ask" },
  { label: "دلار / ین ژاپن", symbol: "usd-jpy-ask" },
  { label: "دلار / فرانک سوییس", symbol: "usd-chf-ask" },
  { label: "دلار استرالیا / دلار", symbol: "aud-usd-ask" },
  { label: "دلار / دلار کانادا", symbol: "usd-cad-ask" },
  { label: "دلار نیوزیلند / دلار", symbol: "nzd-usd-ask" },
  { label: "دلار / دلار سنگاپور", symbol: "usd-sgd-ask" },
  { label: "دلار / روبل روسیه", symbol: "usd-rub-ask" },
  { label: "دلار / درهم امارات", symbol: "usd-aed-ask" },
  { label: "رئال برزیل / دلار", symbol: "brl-usd-ask" },
  { label: "دلار / لیره ترکیه", symbol: "usd-try-ask" },
  { label: "دلار / کرون سوئد", symbol: "usd-sek-ask" },
  { label: "دلار / یوان چین", symbol: "usd-cny-ask" },
  { label: "دلار / پزوی مکزیک", symbol: "usd-mxn-ask" },
  { label: "بیت کوین", symbol: "crypto-bitcoin" },
  { label: "اتریوم", symbol: "crypto-ethereum" },
  { label: "ریپل", symbol: "crypto-ripple" },
  { label: "ای او اس", symbol: "crypto-eos" },
  { label: "بیت کش", symbol: "crypto-bitcoin-cash" },
  { label: "لایت کوین", symbol: "crypto-litecoin" },
  { label: "کاردانو", symbol: "crypto-cardano" },
  { label: "استلار", symbol: "crypto-stellar" },
  { label: "آیوتا", symbol: "crypto-iota" },
  { label: "نئو", symbol: "crypto-neo" },
  { label: "مونرو", symbol: "crypto-monero" },
  { label: "دش", symbol: "crypto-dash" },
  { label: "نم", symbol: "crypto-nem" },
  { label: "کوانتوم", symbol: "crypto-qtum" },
  { label: "لیسک", symbol: "crypto-lisk" },
  { label: "میانگین وزنی برنت ", symbol: "brent-weighted-average" },
  { label: "نفت برنت (بازار آمریکا)", symbol: "energy-brent-oil-contracts" },
  { label: "نفت خام WTI (بازار آمریکا)", symbol: "energy-crude-oil-contracts" },
  { label: "نفت خام WTI  ICE", symbol: "energy-crude-oil-wti-ice" },
  { label: "نفت خام E-Mini", symbol: "energy-e-mini-crude-oil" },
  { label: "بنزین RBOB", symbol: "energy-gasoline-rbob-contracts" },
  { label: "گاز طبیعی (بازار آمریکا)", symbol: "energy-natural-gas-contracts" },
  { label: "گازوییل گوگرد پایین", symbol: "energy-ice-gas-oil-sulphur" },
  { label: "گاز طبیعی E-Mini", symbol: "energy-e-mini-natural-gas" },
  { label: "نفت کوره (بازار آمریکا)", symbol: "energy-heating-oil-contracts" },
  { label: "ذغال سنگ EUA", symbol: "energy-carbon-emissions-contracts" },
  { label: "ذغال سنگ ICE  CSX", symbol: "energy-coal-cme-contracts" },
  { label: "روغن پالم", symbol: "energy-crude-palm-oil-contracts" },
  { label: "گیددینگز", symbol: "giddings" },
  { label: "سواحل غربی ANS ", symbol: "ans-west-coast" },
  { label: "کوستال گرید A", symbol: "coastal-grade-a" },
  { label: "سواحل خلیج HSFO", symbol: "gulf-coast-hsfo" },
  { label: "نفت اوکلاهما", symbol: "oklahoma-intermediate" },
  { label: "نفت ترش اوکلاهما", symbol: "oklahoma-sour" },
  { label: "نفت شیرین اوکلاهما", symbol: "oklahoma-sweet" },
  { label: "وسترن اوکلاهما Swt", symbol: "western-oklahoma-swt" },
  { label: "فوق سنگین آرکانزاس", symbol: "arkansas-ex-heavy" },
  { label: "نفت ترش آرکانزاس", symbol: "arkansas-sour" },
  { label: "نفت شیرین آرکانزاس", symbol: "arkansas-sweet" },
  { label: "نفت غرب تگزاس WTI", symbol: "west-texas-intermediate" },
  { label: "نفت غرب تگزاس / نیومکزیکو", symbol: "w-tx-n-mex-inter" },
  { label: "نفت سبک جنوب تگزاس", symbol: "south-texas-light" },
  { label: "نفت سنگین جنوب تگزاس", symbol: "south-texas-heavy" },
  { label: "میادین مرکزی غرب تگزاس", symbol: "w-cen-tx-inter" },
  { label: "نفت شیرین شرق تگزاس", symbol: "east-texas-sweet" },
  { label: "نفت شیرین شمال تگزاس", symbol: "north-texas-sweet" },
  { label: "نفت ترش غرب تگزاس", symbol: "west-texas-sour" },
  { label: "نفت ترش جنوب تگزاس", symbol: "south-texas-sour" },
  { label: "میعانات ایگل فورد", symbol: "eagle-ford-condensate" },
  { label: "میادین بالادستی تگزاس", symbol: "upper-texas-gulf-coast" },
  { label: "میادین بالادستی خلیج", symbol: "tx-upper-gulf-coast" },
  { label: "میادین بوئنا ویستا", symbol: "buena-vista" },
  { label: "میادین میدوی-سانست", symbol: "midway-sunset" },
  { label: "نفت شیرین کانزاس NW ", symbol: "nw-kansas-sweet" },
  { label: "نفت شیرین کانزاس SW ", symbol: "sw-kansas-sweet" },
  { label: "نفت جنوب شرقی کلرادو", symbol: "colorado-south-east" },
  { label: "نفت لوئیزیانای جنوبی", symbol: "south-louisiana" },
  { label: "نفت شیرین لوئیزیانا", symbol: "north-louisiana-sweet" },
  { label: "نفت لوئیزیانا Delhi/N", symbol: "delhi-n-louisiana" },
  { label: "نفت ترش میشیگان", symbol: "michigan-sour" },
  { label: "نفت شیرین میشیگان", symbol: "michigan-sweet" },
  { label: "نفت شیرین نبراسکا", symbol: "nebraska-sweet" },
  { label: "نفت ترش وایومینگ", symbol: "wyoming-general-sour" },
  { label: "نفت شیرین وایومینگ", symbol: "wyoming-general-sweet" },
  { label: "نفت کساک", symbol: "cossack-1" },
  { label: "سبد نفتی هند", symbol: "indian-basket" },
  { label: "گاز طبیعی هلند", symbol: "dutch-ttf-natural-gas" },
  { label: "نفت تاپیس", symbol: "tapis-malaysia" },
  { label: "نفت سنگین بصره", symbol: "basrah-heavy-1" },
  { label: "نفت موربان امارات", symbol: "murban" },
  { label: "نفت سنگین ایران", symbol: "iran-heavy-2" },
  { label: "نفت ساحاران الجزایر", symbol: "saharan-blend" },
  { label: "نفت سبک نیجریه", symbol: "bonny-light" },
  { label: "نفت گیراسول آنگولا", symbol: "girassol" },
  { label: "نفت سبک عربستان", symbol: "arab-light" },
  { label: "نفت کویت", symbol: "kuwait-export-blend" },
  { label: "نفت سبک  ایران", symbol: "iran-light" },
  { label: "نفت میدان فروزان", symbol: "forozan-blend-2" },
  { label: "نفت سبک ایران", symbol: "iran-light-2" },
  { label: "نفت میدان سروش", symbol: "soroosh" },
  { label: "سبد نفتی مکزیک", symbol: "mexican-basket" },
  { label: "مایا", symbol: "maya-3" },
  { label: "ایست موس", symbol: "isthmus-3" },
  { label: "اولمکا", symbol: "olmeca-1" },
  { label: "وسترن کانادا", symbol: "western-canadian-select" },
  { label: "گاز طبیعی آلبرتا", symbol: "alberta-natural-gas" },
  { label: "نفت خام شیرین", symbol: "sweet-crude" },
  { label: "نفت شیرین سین کرود", symbol: "syncrude-sweet-premium" },
  { label: "نفت ترش سبک", symbol: "light-sour-blend" },
  { label: "نفت ترش پییس", symbol: "peace-sour" },
  { label: "نفت میدیل", symbol: "midale" },
  { label: "نفت آلبرتای مرکزی", symbol: "central-alberta" },
  { label: "نفت شیرین کلیربراک ", symbol: "us-high-sweet-clearbrook" },
  { label: "نفت ترکیبی سنگین آلبین", symbol: "albian-heavy-synthetic" },
  { label: "میدان نفتی داچینگ", symbol: "daqing" },
  { label: "میدان نفتی شنگلی", symbol: "shengli" },
  { label: "نفت دریای جنوبی چین", symbol: "south-china-sea" },
  { label: "نفت دالیا", symbol: "dalia" },
  { label: "نفت نمبا", symbol: "nemba-1" },
  { label: "نفت کابیندا", symbol: "cabinda-1" },
  { label: "نفت سینتا", symbol: "cinta" },
  { label: "نفت دوری", symbol: "duri" },
  { label: "نفت میناس", symbol: "minas" },
  { label: "نفت سنگین عربستان", symbol: "arab-heavy-1" },
  { label: "نفت میان وزن عربستان", symbol: "arab-medium" },
  { label: "نفت فوق سبک عربستان", symbol: "arab-extra-light-1" },
  { label: "نفت دوبی", symbol: "dubai" },
  { label: "میدان نفتی داس", symbol: "das-1" },
  { label: "نفت قطر", symbol: "qatar-land-qatar-1" },
  { label: "نفت مارین قطر", symbol: "marine" },
  { label: "میدان نفتی الشاهین قطر", symbol: "al-shaheen-qatar-1" },
  { label: "نفت کوا آیبو", symbol: "qua-iboe-1" },
  { label: "میدان براس ریور", symbol: "brass-river-1" },
  { label: "میدان نفتی سوکول", symbol: "sokol" },
  { label: "میدان نفتی اسپو", symbol: "espo" },
];

export const DEFAULT_ASSET_SYMBOL = "geram18";

export const TSETMC_INDICES: IndexOption[] = [
  { label: "زراعت", insCode: "34408080767216529" },
  { label: "ذغال سنگ", insCode: "19219679288446732" },
  { label: "كانه فلزي", insCode: "13235969998952202" },
  { label: "ساير معادن", insCode: "62691002126902464" },
  { label: "منسوجات", insCode: "59288237226302898" },
  { label: "محصولات چرمي", insCode: "69306841376553334" },
  { label: "محصولات چوبي", insCode: "58440550086834602" },
  { label: "محصولات كاغذ", insCode: "30106839080444358" },
  { label: "انتشار و چاپ", insCode: "25766336681098389" },
  { label: "فراورده نفتي", insCode: "12331083953323969" },
  { label: "لاستيك", insCode: "36469751685735891" },
  { label: "فلزات اساسي", insCode: "32453344048876642" },
  { label: "محصولات فلزي", insCode: "1123534346391630" },
  { label: "ماشين آلات", insCode: "11451389074113298" },
  { label: "دستگاههاي برقي", insCode: "33878047680249697" },
  { label: "وسايل ارتباطي", insCode: "24733701189547084" },
  { label: "ابزار پزشكي", insCode: "61848754958448778" },
  { label: "خودرو", insCode: "20213770409093165" },
  { label: "حمل و نقل", insCode: "24187097921483699" },
  { label: "مبلمان", insCode: "29331053506731535" },
  { label: "قند و شكر", insCode: "21948907150049163" },
  { label: "چند رشته اي ص", insCode: "40355846462826897" },
  { label: "تامين آب، برق، گاز", insCode: "54843635503648458" },
  { label: "غذايي بجز قند", insCode: "15508900928481581" },
  { label: "مواد دارويي", insCode: "3615666621538524" },
  { label: "شيميايي", insCode: "33626672012415176" },
  { label: "پيمانكاري", insCode: "41934470778361119" },
  { label: "47خرده فروشي به جز وسايل نقليه", insCode: "65986638607018835" },
  { label: "كاشي و سراميك", insCode: "57616105980228781" },
  { label: "سيمان", insCode: "70077233737515808" },
  { label: "كاني غيرفلزي", insCode: "14651627750314021" },
  { label: "هتل و رستوران", insCode: "64514606457616199" },
  { label: "سرمايه گذاريها", insCode: "34295935482222451" },
  { label: "بانكها", insCode: "72002976013856737" },
  { label: "سايرمالي", insCode: "25163959460949732" },
  { label: "راديويي", insCode: "41867092385281437" },
  { label: "مالي", insCode: "61247168213690670" },
  { label: "اداره بازارهاي مالي", insCode: "61985386521682984" },
  { label: "انبوه سازي", insCode: "4654922806626448" },
  { label: "رايانه", insCode: "8900726085939949" },
  { label: "اطلاعات و ارتباطات", insCode: "18780171241610744" },
  { label: "فني مهندسي", insCode: "47233872677452574" },
  { label: "استخراج نفت جزكشف11", insCode: "65675836323214668" },
  { label: "بيمه و بازنشسته66", insCode: "59105676994811497" },
  { label: "شاخص 30 شركت بزرگ", insCode: "10523825119011581" },
  { label: "شاخص آزاد شناور", insCode: "49579049405614711" },
  { label: "شاخص بازار اول", insCode: "62752761908615603" },
  { label: "شاخص بازار دوم", insCode: "71704845530629737" },
  { label: "شاخص صنعت", insCode: "43754960038275285" },
  { label: "شاخص قيمت (هم وزن)", insCode: "8384385859414435" },
  { label: "شاخص قيمت 50 شركت", insCode: "69932667409721265" },
  { label: "شاخص قيمت(وزني-ارزشي)", insCode: "5798407779416661" },
  { label: "شاخص كل", insCode: "32097828799138957" },
  { label: "شاخص كل (هم وزن)", insCode: "67130298613737946" },
  { label: "شاخص50شركت فعالتر", insCode: "46342955726788357" },
];

export const DEFAULT_INDEX_INS_CODE = "67130298613737946"; // شاخص كل (هم وزن) / total_ew
